baseURL = "https://jasonw66.github.io/blog/"
languageCode = "zh-cn"
title = "我的 Hugo 博客"

[module]
  [[module.imports]]
    path = "github.com/gethinode/hinode"

[params]
  description = "这是我的个人博客"
  author = "JasonW66"